language: node_js
node_js:
  - 10.15.0

# if using Ubuntu 16 need this library
# https://github.com/cypress-io/cypress-documentation/pull/1647
addons:
  apt:
    packages:
      - libgconf-2-4

install:
  - npm ci
  # seems like we have to do client side too
  - npm run heroku-prebuild

cache:
  npm: true
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm

before_script:
  - npm run develop:ci -- --silent &

script:
  - set -e
  - npm run test
  - npm run test:e2e:ci
